ALTER TABLE users
    MODIFY COLUMN username VARCHAR(255) NOT NULL AFTER id,
    MODIFY COLUMN full_name VARCHAR(255) NOT NULL AFTER username,
    MODIFY COLUMN email VARCHAR(255) NOT NULL AFTER full_name,
    MODIFY COLUMN password VARCHAR(255) NOT NULL AFTER email;
